##
## Concept    : NLP Text Preprocessing & BERT Embeddings (Local — No OpenAI API)
## What it does: Preprocesses two sentences using classic NLP techniques (tokenization,
##               stop word removal, lemmatization), then generates BERT embeddings for
##               each using HuggingFace Transformers and PyTorch.
## What you'll learn:
##   - Text preprocessing pipeline:
##       1. Tokenization — split text into individual words
##       2. Stop word removal — remove common words ("the", "a", "is") that carry little meaning
##       3. Lemmatization — reduce words to their base form ("running" -> "run")
##   - How BERT tokenizes text differently from simple word splitting (wordpiece tokenization)
##   - The CLS token: BERT adds a special [CLS] token at the start of every input.
##     Its embedding from the last hidden layer is used as a fixed-size representation
##     of the entire input sequence — this is what we extract as the sentence embedding.
##   - torch.no_grad(): disables gradient computation during inference to save memory
## Note: Downloads ~440MB BERT model on first run. No OpenAI API key required.
## Run: python 13.bert_sample.py
##
import nltk
# Download required NLTK corpora on first run (no-op if already present)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from transformers import BertTokenizer, BertModel
import string
import numpy as np
import torch

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    """Preprocess the input text by tokenizing, removing stop words, and lemmatizing."""

    # Convert text sequence into individual words called tokens
    print("Original text:\n", text, "\n")

    # Tokenize the text
    tokens = word_tokenize(text.lower())

    print("Original text tokens:\n", tokens, "\n")

    # Extract stop_words and remove punctutaion from the tokens and lemmatize the reamining tokens
    tokens = [lemmatizer.lemmatize(token) for token in tokens if token not in stop_words and token not in string.punctuation]

    print("Tokens we have after removing stop words, punctuation and lemmatization:\n", tokens, "\n")

    # Join the new lemma token
    return ' '.join(tokens)

# Sample data
Text_sequences = ["We had a picnic on the river bank.",
"Tom deposited his paycheck into his savings bank account."
]

preprocessed_Text_sequences = [preprocess_text(text) for text in Text_sequences]

print("Preprocessed Text Sequences:\n", preprocessed_Text_sequences)

# The preprocessed text is further tokenized by a BERT tokenizer, converting the data into a format the BERT model takes as input to generate embeddings for each BERT-generated token

# Load pre-trained BERT tokenizer
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
print("BERT Tokenizer:\n", bert_tokenizer)

# Load the pretrained BERT model
bert_model = BertModel.from_pretrained('bert-base-uncased')

def generate_embedding(preprocessed_text_sequence):
    print("Preprocessed text sequence:\n", preprocessed_text_sequence)
    # Encoding the preprocessed text in the format expected by BERT. 'pt' stands for PyTorch tensor, for tensorflow tensor, this value would be 'tf'
    inputs = bert_tokenizer(preprocessed_text_sequence, return_tensors='pt')
    print("BERT tokenized input tensor that will later be given as input to the BERT model:\n", inputs)
    # Visualizing the tokens generated by BERT from preprocessed text sequence
    bert_tokenized_text = bert_tokenizer.convert_ids_to_tokens(inputs['input_ids'][0])
    print("BERT tokens:\n", bert_tokenized_text)
    print("Number of BERT tokens:\n", len(bert_tokenized_text))
    # Forward pass, get hidden states
    with torch.no_grad():
        outputs = bert_model(**inputs)
        # The last hidden state of the BERT model gives us the embeddings for each word/token in the input sequence. The shape of the last hidden state is (batch_size, sequence_length, hidden_size). Since we are interested in the embedding for the [CLS] token, which is the first token in the sequence, we extract it using outputs.last_hidden_state[:, 0, :]. This gives us a tensor of shape (hidden_size,) representing the embedding for the [CLS] token.
        cls_embedding = outputs.last_hidden_state[:, 0, :].squeeze()
        print("CLS embeddings shape: ", cls_embedding.shape)
        print("BERT CLS embedding: ", cls_embedding)
        return cls_embedding.numpy()

# Tokenize the preprocessed text sequences using BERT tokenizer
for preprocessed_text_sequence in preprocessed_Text_sequences:
    print("Generating BERT embedding for the preprocessed text sequence:\n", preprocessed_text_sequence, "\n")
    embedding = generate_embedding(preprocessed_text_sequence)
    print("BERT embedding for the preprocessed text sequence:\n", embedding, "\n")

##
## Expected output (truncated — embeddings are 768 numbers):
##   Original text:
##    We had a picnic on the river bank.
##
##   Original text tokens:
##    ['we', 'had', 'a', 'picnic', 'on', 'the', 'river', 'bank', '.']
##
##   Tokens after removing stop words, punctuation and lemmatization:
##    ['picnic', 'river', 'bank']
##
##   BERT tokens:
##    ['[CLS]', 'pic', '##nic', 'river', 'bank', '[SEP]']
##
##   CLS embeddings shape: torch.Size([768])
##   BERT CLS embedding: [-0.1532  0.3421  0.0892 ... ] (768 values)
##
## Note: "bank" is ambiguous (river bank vs savings bank). BERT embeddings for the two
## sentences will differ because BERT uses context to assign meaning.
##
## Challenges:
##   1. Add a third sentence like "She went to the bank to deposit money" and compare
##      its embedding to both existing sentences using cosine similarity
##   2. Remove the preprocessing step and pass raw text directly to BERT — does it matter?
##   3. Print the BERT tokens for both sentences side by side to see how wordpiece
##      tokenization handles the word "bank" differently based on context
##   4. Try bert-base-multilingual-cased instead of bert-base-uncased for non-English text
##
