##
## Concept    : Semantic Job Search Using BERT Embeddings (Local — No OpenAI API)
## What it does: Loads a CSV of job descriptions, preprocesses the text, generates BERT
##               embeddings for each job, then ranks jobs by semantic similarity to a query.
## What you'll learn:
##   - End-to-end semantic search pipeline:
##       1. Load & preprocess text data with pandas and NLTK
##       2. Generate BERT embeddings for all documents (job descriptions)
##       3. Generate an embedding for the search query
##       4. Rank documents by cosine similarity to the query
##   - Performance optimization: pre-compute all job embeddings once at startup so that
##     each search query only requires one embedding call, not N calls
##   - Truncation in BERT tokenization: BERT has a 512-token limit — long job descriptions
##     must be truncated to avoid index out-of-range errors
##   - How semantic search differs from keyword search: a query for "python developer"
##     can match a job described as "software engineer" if the embeddings are close
## Prerequisite: job_title_des.csv or job_descriptions.csv must exist in this directory
##              with columns: "Job Title" and "Job Description"
## Note: Downloads ~440MB BERT model on first run. No OpenAI API key required.
## Run: python 14.find_matching_jobs.py
##
import nltk
# Download required NLTK corpora on first run (no-op if already present)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)

import numpy as np
import pandas as pd
import torch
from pathlib import Path
from transformers import BertTokenizer, BertModel
from sklearn.metrics.pairwise import cosine_similarity
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

def load_dataset():
    script_dir = Path(__file__).resolve().parent
    candidate_files = [
        script_dir / "data" / "job_title_des.csv",
        script_dir / "data" / "job_descriptions.csv",
    ]

    for csv_path in candidate_files:
        if csv_path.exists():
            return pd.read_csv(csv_path)

    raise FileNotFoundError(
        "No dataset CSV found. Expected one of: "
        f"{', '.join(str(path.name) for path in candidate_files)} in {script_dir}"
    )

# Load dataset from CSV file
try:
    df = load_dataset()
except FileNotFoundError as e:
    raise SystemExit(f"Error: {e}")

# Limit rows for faster demo runs. Set to None to process the full dataset.
MAX_ROWS = 20
if MAX_ROWS is not None:
    df = df.head(MAX_ROWS)

# Preprocess text data
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    tokens = word_tokenize(text.lower())
    tokens = [lemmatizer.lemmatize(token) for token in tokens if token not in stop_words and token not in string.punctuation]
    return ' '.join(tokens)

df['processed_description'] = df['Job Description'].apply(preprocess_text)

# Load pretrained BERT tokenizer and model
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = BertModel.from_pretrained('bert-base-uncased')

# tokenizes the job description text, feeds it to BERT, and extracts embedding for it using the [CLS] token embedding.
# While doing tokenization, we need to set the truncation parameter to True as long descriptions will result in generating an error that the token index sequence length is longer than the specified maximum sequence length for this model, which is 512. Running such a sequence through the model will result in indexing errors. Setting this parameter will truncate the sequences larger than the maximum sequence length the model allows.
def generate_embedding(text):
    inputs = bert_tokenizer(text, return_tensors='pt', truncation=True, max_length=512)
    with torch.no_grad():
        outputs = bert_model(**inputs)
        # It generates the output of the BERT model for the given input text. The output includes various hidden states and embeddings generated by the model. The specific output we are interested in is the embedding corresponding to the [CLS] token, which is typically used as a representation of the entire input sequence for classification tasks. We extract this embedding from the last hidden state of the model's output.
    cls_embedding = outputs.last_hidden_state[:, 0, :].squeeze().numpy()
    return cls_embedding

# Pre-compute job description embeddings once so semantic_search doesn't recompute them on every call
print("Pre-computing job description embeddings...")
job_embeddings = [generate_embedding(desc) for desc in df['processed_description']]

# performing a semantic search using BERT embeddings. It computes cosine similarity between the query embedding and pre-computed job description embeddings to find the most similar jobs.
def semantic_search(query, top_n=3):
    query_embedding = generate_embedding(query)
    similarities = []
    for idx, (_, row) in enumerate(df.iterrows()):
        similarity = cosine_similarity([query_embedding], [job_embeddings[idx]])[0][0]
        similarities.append((row['Job Title'], similarity, row['Job Description']))
    similarities.sort(key=lambda x: x[1], reverse=True)
    return similarities[:top_n]

# Example usage
query = "python developer with experience in web development"
results = semantic_search(query)
for title, similarity, description in results:
    print(f"Title: {title}, Similarity: {similarity:.2f}")

##
## Expected output (titles depend on your CSV data):
##   Pre-computing job description embeddings...
##   Title: Software Engineer - Python, Similarity: 0.91
##   Title: Full Stack Web Developer, Similarity: 0.87
##   Title: Backend Engineer, Similarity: 0.83
##
## Challenges:
##   1. Change MAX_ROWS to None to process all rows in your dataset
##   2. Try different search queries: "machine learning engineer", "data analyst", "devops"
##   3. Add a similarity threshold (e.g. only show results with similarity > 0.80)
##   4. Add a second search query and compare its top results to the first — notice how
##      semantically different queries return different rankings even on the same dataset
##
    



