##
## Concept    : Multi-Turn Conversations & Token Tracking
## What it does: An interactive programming help chatbot that remembers the full conversation
##               history across multiple turns and tracks cumulative token usage.
## What you'll learn:
##   - Why conversation history matters: the API is stateless, so you must send all
##     previous messages on every request to give the model context
##   - How to grow the messages list by appending both user and assistant messages each turn
##   - How token usage accumulates over a long conversation (important for cost awareness)
##   - The role of the system message in shaping the assistant's personality/scope
##   - Token breakdown per turn:
##       prompt_tokens    = all tokens sent to the model (grows as history grows)
##       completion_tokens = new tokens generated by the model this turn
##       total_tokens     = prompt_tokens + completion_tokens for this API call
## Run: python 5.multi_turn_chatbot.py
##
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

client = OpenAI()

messages=[
    {"role": "system", "content": "You are a programming expert. Answer questions about programming languages. Keep responses short, concise and to the point."}
]

over_all_usage_tokens = 0

print("Welcome to the Programming Help chatbot. Ask me a question!")
while True:
    user_question = input("You: ")
    if user_question.lower() in ["exit", "quit", "bye", "tata"]:
        print("Chatbot: Goodbye! Have a great day!")
        break
    user_message = {"role": "user", "content": user_question}

    messages.append(user_message)

    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=messages,
    )

    prompt_tokens = response.usage.prompt_tokens
    completion_tokens = response.usage.completion_tokens
    total_tokens = response.usage.total_tokens
    # Accumulate only completion_tokens — prompt_tokens include the entire history
    # re-sent each turn, so summing total_tokens would double-count past context.
    over_all_usage_tokens += completion_tokens

    assistant_reply = response.choices[0].message.content.strip()

    print("Chat Assistant: ", assistant_reply, "\n")
    print(f"Tokens this turn — prompt: {prompt_tokens}, completion: {completion_tokens}, total: {total_tokens}\n")

    assistant_message = {"role":"assistant", "content": assistant_reply}

    messages.append(assistant_message)

    

print(f"Total completion tokens generated across all turns: {over_all_usage_tokens}")

##
## Expected output (sample session):
##   Welcome to the Programming Help chatbot. Ask me a question!
##   You: What is a list in Python?
##   Chat Assistant: A list is an ordered, mutable collection of items. Example: my_list = [1, 2, 3]
##
##   Tokens this turn — prompt: 38, completion: 21, total: 59
##
##   You: How is it different from a tuple?
##   Chat Assistant: A tuple is like a list but immutable — you can't change it after creation.
##
##   Tokens this turn — prompt: 70, completion: 18, total: 88
##                               ^^^ grows each turn as history is re-sent
##
##   You: bye
##   Chatbot: Goodbye! Have a great day!
##   Total completion tokens generated across all turns: 39
##
## Challenges:
##   1. Add a /clear command that resets the messages list (keeps the system message)
##   2. Add a /history command that prints all messages exchanged so far
##   3. Cap the conversation at 10 turns — after that, print a warning and exit gracefully
##   4. Track the cost: gpt-4.1-mini charges ~$0.40 per 1M completion tokens. Print estimated cost at the end.
##
